FROM python:3.8

SHELL ["/bin/bash", "-c"]

RUN useradd --no-log-init --system --create-home customer

WORKDIR /app

COPY ./requirements.txt ./requirements.txt
COPY ./requirements-dev.txt ./requirements-dev.txt

RUN pip install -r requirements-dev.txt